# -*- coding: utf-8 -*-
"""
Cursor Settings 页面汉化工具
功能：将翻译脚本注入 Cursor 的 workbench.html，实现设置页面中文化
用法：python CursorHanHua_GongJu.py [--huifu]
      --huifu  恢复原始文件
"""

import os  # 文件路径操作
import sys  # 系统参数
import shutil  # 文件复制
import datetime  # 时间戳
import hashlib  # 哈希计算
import base64  # Base64 编码
import json  # JSON 读写

# ============================================================
# ★★★ 用户配置区域 ★★★
# 如果您的 Cursor 安装在其他位置，请修改下面的路径
# ============================================================

# Cursor 安装根目录（修改为您的实际安装路径）
# 例如：r"C:\Users\用户名\AppData\Local\Programs\cursor"
#       r"D:\Tools\cursor"
CURSOR_AN_ZHUANG_LU_JING = r"D:\Tools\cursor"

# 以下路径一般不需要修改（除非 Cursor 内部结构发生重大变化）
GONG_ZUO_TAI_HTML_XIANG_DUI = r"resources\app\out\vs\code\electron-sandbox\workbench"  # workbench 目录相对路径
GONG_ZUO_TAI_HTML_MING = "workbench.html"  # workbench HTML 文件名
HAN_HUA_JS_MING = "cursor_hanhua.js"  # 翻译脚本文件名
ZHU_RU_BIAO_JI = "<!-- CURSOR_HANHUA_INJECTION -->"  # 注入标记，用于检测是否已注入
BEI_FEN_HOU_ZHUI = ".bak"  # 备份文件后缀

# ============================================================
# 完整的翻译 JavaScript 代码（内嵌）
# ============================================================
HAN_HUA_JS_NEI_RONG = '''\
/*
 * Cursor Settings Page - Chinese Translation Script
 * Auto-generated by CursorHanHua_GongJu.py
 */
(function() {
    'use strict';

    var FanYi_CiDian = new Map([
        // ==================== 左侧导航栏 ====================
        ["General", "通用"],
        ["Agents", "智能体"],
        ["Tab", "代码补全"],
        ["Cloud Agents", "云端智能体"],
        ["Plugins", "插件"],
        ["Rules, Skills, Subagents", "规则、技能、子智能体"],
        ["Tools & MCP", "工具与 MCP"],
        ["Hooks", "钩子"],
        ["Indexing & Docs", "索引与文档"],
        ["Network", "网络"],
        ["Marketplace", "市场"],
        ["Beta", "测试版"],
        ["Features", "功能"],
        ["Models", "模型"],
        ["Rules", "规则"],
        ["Docs", "文档"],
        ["Search settings Ctrl+F", "搜索设置 Ctrl+F"],
        ["Search settings", "搜索设置"],
        ["Pro Plan", "专业版计划"],

        // ==================== 通用 (General) 页面 ====================
        // -- 账户区域 --
        ["Account", "账户"],
        ["Sign In", "登录"],
        ["Sign Out", "退出登录"],
        ["Log In", "登录"],
        ["Log Out", "退出登录"],
        ["Logout", "退出登录"],
        ["Manage Subscription", "管理订阅"],
        ["Manage Account", "管理账户"],
        ["Manage", "管理"],
        ["Manage your account and billing", "管理您的账户和账单"],
        ["Plan & Usage", "计划与用量"],
        ["Upgrade", "升级"],
        ["Upgrade to Pro", "升级到专业版"],
        ["Upgrade to Pro now", "立即升级到专业版"],
        ["Upgrade Plan", "升级计划"],
        ["Free", "免费版"],
        ["Pro", "专业版"],
        ["Business", "企业版"],
        ["Usage", "用量"],
        ["On-Demand", "按需"],
        ["On-Demand Spending", "按需消费"],
        ["On-Demand Usage", "按需用量"],
        ["On-demand spending is currently disabled", "按需消费目前已禁用"],
        ["On-Demand usage is consumed after a usage limit is reached, and is billed in arrears.", "按需用量在达到使用限额后消耗，采用后付费方式计费。"],
        ["Enable on-demand usage to go beyond your plan's included usage. Requires a paid plan.", "启用按需用量以超出计划包含的用量。需要付费计划。"],
        ["Monthly Limit", "每月限额"],
        ["Set a fixed amount or make it unlimited.", "设置固定金额或设为无限制。"],
        ["Fixed", "固定"],
        ["Unlimited", "无限制"],
        ["Total", "合计"],
        ["Unlock 3x more usage on Agent & more", "解锁 Agent 3 倍用量及更多"],
        ["Free 7-day trial", "免费 7 天试用"],
        ["Start Plan Now", "立即开始计划"],
        ["Start Pro Now", "立即开始专业版"],
        ["Start Pro+ Now", "立即开始 Pro+"],
        ["Get Pro+", "获取 Pro+"],
        ["Get Ultra", "获取 Ultra"],
        ["Sign in to get started with Cursor's AI features", "登录以开始使用 Cursor 的 AI 功能"],

        // -- 隐私与遥测 --
        ["Privacy", "隐私"],
        ["Privacy Mode", "隐私模式"],
        ["Privacy mode", "隐私模式"],
        ["Privacy Mode Enabled", "隐私模式已启用"],
        ["Privacy Mode (Legacy)", "隐私模式（旧版）"],
        ["Enable Privacy Mode", "启用隐私模式"],
        ["Share Data", "共享数据"],
        ["Data Sharing Enabled", "数据共享已启用"],
        ["When enabled, none of your code will ever be stored by us.", "启用后，我们将不会存储您的任何代码。"],
        ["None of your code will be stored by us.", "我们不会存储您的任何代码。"],
        ["Your code may be used for training.", "您的代码可能会被用于训练。"],
        ["Your code data will not be trained on or used to improve the product. We will not store your code.", "您的代码数据不会被用于训练或用于改进产品。我们不会存储您的代码。"],
        ["Privacy Mode (Legacy) is enabled. Background Agent and some features not available.", "隐私模式（旧版）已启用。后台 Agent 和部分功能不可用。"],
        ["Enabled", "已启用"],
        ["Disabled", "已禁用"],
        ["enabled", "已启用"],
        ["disabled", "已禁用"],
        ["Failed to update privacy settings", "隐私设置更新失败"],
        ["Hide Email Address", "隐藏邮箱地址"],
        ["Hide Email", "隐藏邮箱"],
        ["Partially mask your email address in the Cursor user interface", "在 Cursor 用户界面中部分隐藏您的邮箱地址"],
        ["Share Now", "立即共享"],
        ["Switch to Privacy Mode", "切换到隐私模式"],
        ["Data Sharing is paused for your first day of usage.", "数据共享在您使用的第一天暂停。"],
        ["No training. Code may be stored for Background Agent and other features.", "不用于训练。代码可能会为后台 Agent 和其他功能而存储。"],
        ["No training and no storage. Background Agent and other features that require code storage will be disabled.", "不用于训练且不存储。后台 Agent 和其他需要代码存储的功能将被禁用。"],
        ["Cloud Agents are not available when your privacy mode is set to disable data storage. To use Cloud Agents, please update your privacy settings to allow data storage.", "当隐私模式设置为禁止数据存储时，云端智能体不可用。要使用云端智能体，请更新隐私设置以允许数据存储。"],
        ["Cloud Agents require data storage to function.", "云端智能体需要数据存储才能运行。"],
        ["Cloud Agents are disabled because your privacy mode prevents data storage. Update your privacy settings to enable Cloud Agents.", "由于您的隐私模式阻止了数据存储，云端智能体已被禁用。请更新隐私设置以启用云端智能体。"],

        // -- 编辑器/外观 --
        ["Appearance", "外观"],
        ["Editor", "编辑器"],
        ["Editor Settings", "编辑器设置"],
        ["Editor (Classic)", "编辑器（经典）"],
        ["Configure font, formatting, minimap and more", "配置字体、格式化、小地图等"],
        ["Theme", "主题"],
        ["Keyboard Shortcuts", "键盘快捷键"],
        ["Configure keyboard shortcuts", "配置键盘快捷键"],
        ["Color Theme", "颜色主题"],
        ["File Icon Theme", "文件图标主题"],
        ["Product Icon Theme", "产品图标主题"],
        ["Font Size", "字体大小"],
        ["Font Family", "字体"],
        ["Line Height", "行高"],
        ["Tab Size", "Tab 大小"],
        ["Word Wrap", "自动换行"],
        ["Auto Save", "自动保存"],
        ["Format On Save", "保存时格式化"],
        ["Minimap", "小地图"],
        ["Breadcrumbs", "面包屑导航"],
        ["Layout", "布局"],
        ["Default Layout", "默认布局"],
        ["Choose the default layout for new windows and workspaces", "选择新窗口和工作区的默认布局"],
        ["Zen", "禅模式"],
        ["Status Bar", "状态栏"],
        ["Show status bar", "显示状态栏"],
        ["Title Bar", "标题栏"],
        ["Show title bar in agent layout", "在智能体布局中显示标题栏"],
        ["Auto-hide editor when empty", "编辑器为空时自动隐藏"],
        ["When all editors are closed, hide the editor area and maximize chat", "当所有编辑器关闭时，隐藏编辑器区域并最大化聊天"],
        ["Sync layouts across windows", "跨窗口同步布局"],
        ["When enabled, all windows share the same layout", "启用后，所有窗口共享相同的布局"],
        ["Review Control Location", "审查控件位置"],
        ["Show inline diff review controls in top level breadcrumbs or floating island", "在顶级面包屑导航或浮动岛中显示内联差异审查控件"],
        ["Open chat as editor tabs", "以编辑器标签页打开对话"],
        ["Show chats as editor tabs inside the chat area instead of the legacy stacked view", "在聊天区域内以编辑器标签页显示对话，而不是旧的堆叠视图"],
        ["Open chat as editor tabs is unavailable while non-chat content is placed in the Secondary Side Bar.", "当非聊天内容放置在辅助侧栏中时，以编辑器标签页打开对话不可用。"],

        // -- 外观 - 颜色 --
        ["Colors", "颜色"],
        ["Hue", "色相"],
        ["Choose a tint color", "选择色调颜色"],
        ["Intensity", "强度"],
        ["Control how strongly the tint is applied", "控制色调的应用强度"],
        ["Reduce Transparency", "减少透明度"],
        ["Replace translucent surfaces with opaque backgrounds", "将半透明表面替换为不透明背景"],

        // -- 外观 - 排版 --
        ["Typography", "排版"],
        ["UI Font Size", "界面字体大小"],
        ["Font size for the Cursor user interface", "Cursor 用户界面的字体大小"],
        ["Code Font Size", "代码字体大小"],
        ["Font size for code editors and diffs", "代码编辑器和差异对比的字体大小"],
        ["UI Font Family", "界面字体"],
        ["Override the Cursor user interface typeface", "覆盖 Cursor 用户界面的字体"],
        ["Code Font Family", "代码字体"],
        ["Override the font for code editors and diffs", "覆盖代码编辑器和差异对比的字体"],
        ["System font", "系统字体"],
        ["System monospace", "系统等宽字体"],

        // -- 外观 - 主题选项 --
        ["Choose between light, dark, or high contrast themes", "在浅色、深色或高对比度主题之间选择"],
        ["High contrast", "高对比度"],
        ["Light", "浅色"],
        ["Dark", "深色"],

        // -- 导入与更新 --
        ["Cursor Account", "Cursor 账户"],
        ["Import Settings from VS Code", "从 VS Code 导入设置"],
        ["Import settings, extensions, and keybindings from VS Code", "从 VS Code 导入设置、扩展和快捷键"],
        ["Importing", "导入中"],
        ["VS Code import completed!", "VS Code 导入完成！"],
        ["Update Access", "更新通道"],
        ["Early Access", "抢先体验"],
        ["Nightly", "每日构建"],
        ["By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.", "默认情况下，您将收到稳定版更新通知。在抢先体验中，预发布版本可能不适合生产使用。"],
        ["Dogfood", "内测版"],
        ["Warning: Updates Apply Automatically", "警告：更新将自动应用"],
        ["This track will silently download and install updates without prompting whenever Cursor is closed.", "此通道将在 Cursor 关闭时静默下载并安装更新，不会提示。"],
        ["Notifications", "通知"],
        ["System Notifications", "系统通知"],
        ["System Tray Icon", "系统任务栏图标"],
        ["Show system notifications when Agent completes or needs attention", "当 Agent 完成或需要关注时显示系统通知"],
        ["Warning Notifications", "警告通知"],
        ["Show warning-level in-app toasts", "显示警告级别的应用内提示"],
        ["Menu Bar Icon", "菜单栏图标"],
        ["Show Cursor in menu bar", "在菜单栏中显示 Cursor"],
        ["Show Cursor in system tray", "在系统托盘中显示 Cursor"],
        ["Show status bar at the bottom of the window", "在窗口底部显示状态栏"],

        // -- 工具栏 --
        ["Toolbar on Selection", "选中时显示工具栏"],
        ["Show Add to Chat & Quick Edit buttons when selecting code", "选中代码时显示[添加到聊天]和[快速编辑]按钮"],

        // -- 内联编辑与终端 --
        ["Inline Editing & Terminal", "内联编辑与终端"],
        ["Cmd+K: Escape focuses the editor when you have a diff", "Cmd+K：有差异时按 Escape 聚焦编辑器"],
        ["Make escape focus editor instead of closing the prompt bar", "让 Escape 聚焦编辑器而不是关闭提示栏"],
        ["Terminal Hint", "终端提示"],
        ["Inline Diffs", "内联差异"],
        ["Show inline diff decorations in the editor instead of only showing changes in the review panel", "在编辑器中显示内联差异装饰，而不仅在审查面板中显示更改"],
        ["Themed Diff Backgrounds", "主题化差异背景"],
        ["Use themed background colors for inline code diffs", "为内联代码差异使用主题化背景颜色"],
        ["Jump to Next Diff on Accept", "接受后跳转到下一个差异"],

        // -- 通知声音 --
        ["Completion Sound", "完成提示音"],
        ["Play a sound when Agent finishes responding", "当 Agent 完成回复时播放提示音"],
        ["Notification Sound", "通知声音"],
        ["Reset to default sound", "重置为默认声音"],
        ["Default sound", "默认声音"],
        ["Browse...", "浏览..."],
        ["Failed to play sound. Please check the file path is valid and the file is a supported audio format (mp3, wav, ogg).", "播放声音失败。请检查文件路径是否有效，以及文件是否为受支持的音频格式（mp3、wav、ogg）。"],

        // -- 开发工具 --
        ["Development", "开发"],
        ["Enable Disposable Tracking", "启用一次性追踪"],
        ["Disposable Tracking", "一次性追踪"],
        ["Enable leak detection console output", "启用内存泄漏检测控制台输出"],
        ["Leak Detection", "内存泄漏检测"],
        ["Solid Dev Tools", "Solid 开发工具"],
        ["Enable Solid Dev Tools", "启用 Solid 开发工具"],
        ["Force View Zones", "强制显示视图区域"],
        ["Force the display of view zones in the editor", "强制在编辑器中显示视图区域"],
        ["Show view zone when preview box is clipped", "预览框被裁剪时显示视图区域"],
        ["Show a view zone when the preview box is clipped", "预览框被裁剪时显示视图区域"],
        ["Extension RPC Tracer", "扩展 RPC 追踪器"],
        ["Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.", "将扩展宿主 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。"],
        ["Optional folder for RPC logs (defaults to logs/exthost)", "RPC 日志的可选文件夹（默认为 logs/exthost）"],
        ["This action enables IDE debug log upload which contains information about IDE behavior itself and is required for bug investigations", "此操作启用 IDE 调试日志上传，其中包含有关 IDE 行为本身的信息，是调查 Bug 所必需的"],

        // -- 扩展安全 --
        ["Extension Security", "扩展安全"],
        ["Verify Extension Signatures", "验证扩展签名"],
        ["Verify extension signatures when installing and loading extensions", "安装和加载扩展时验证扩展签名"],

        // -- 隐藏对话框 --
        ["See warnings and tips that you\\u2019ve hidden", "查看您已隐藏的警告和提示"],
        ["No Hidden Dialogs Yet", "暂无隐藏的对话框"],
        ["Restore", "恢复"],

        // -- 开发登录 --
        ["Dev Login (Free)", "开发登录（免费版）"],
        ["Dev Login (Pro)", "开发登录（专业版）"],
        ["Dev Login (Pro Trial)", "开发登录（专业版试用）"],
        ["Dev Login (Pro Plus)", "开发登录（Pro Plus）"],
        ["Dev Login (Pro Plus Trial)", "开发登录（Pro Plus 试用）"],
        ["Dev Login (Enterprise)", "开发登录（企业版）"],
        ["Dev Login (Ultra)", "开发登录（Ultra）"],
        ["Login with Free for local development", "使用免费版登录进行本地开发"],
        ["Login with Pro plan for local development", "使用专业版登录进行本地开发"],
        ["Login with Pro Trial for local development", "使用专业版试用登录进行本地开发"],
        ["Login with Pro Plus for local development", "使用 Pro Plus 登录进行本地开发"],
        ["Login with Pro Plus Trial for local development", "使用 Pro Plus 试用登录进行本地开发"],
        ["Login with Enterprise (team) for local development", "使用企业版（团队）登录进行本地开发"],
        ["Login with Ultra plan for local development", "使用 Ultra 登录进行本地开发"],
        ["Enterprise Login", "企业版登录"],
        ["Free Login", "免费版登录"],
        ["Pro Login", "专业版登录"],
        ["Pro Plus Login", "Pro Plus 登录"],
        ["Pro Plus Trial Login", "Pro Plus 试用登录"],
        ["Pro Trial Login", "专业版试用登录"],
        ["Ultra Login", "Ultra 登录"],

        // ==================== 智能体 (Agents) 页面 ====================
        ["Auto-Run", "自动运行"],
        ["Auto-Run Mode", "自动运行模式"],
        ["Choose how Agent runs tools like command execution, MCP, and file writes.", "选择 Agent 如何运行工具（如命令执行、MCP 和文件写入）。"],
        ["Choose how Agent runs tools like command execution, MCP, and file writes", "选择 Agent 如何运行工具（如命令执行、MCP 和文件写入）"],
        ["Run Everything", "运行所有"],
        ["Run Everything (Unsandboxed)", "运行所有（无沙盒）"],
        ["Ask Every Time", "每次询问"],
        ["Auto-Run in Sandbox", "在沙盒中自动运行"],
        ["Use Allowlist", "使用白名单"],
        ["Auto-Approved Mode Transitions", "自动批准模式切换"],
        ["Mode transitions that will be automatically approved without prompting.", "将自动批准而无需提示的模式切换。"],
        ["Mode transitions that will be automatically approved without prompting", "将自动批准而无需提示的模式切换"],
        ["Browser Protection", "浏览器保护"],
        ["Prevent Agent from automatically running Browser tools", "阻止 Agent 自动运行浏览器工具"],
        ["MCP Tools Protection", "MCP 工具保护"],
        ["Prevent Agent from automatically running MCP tools", "阻止 Agent 自动运行 MCP 工具"],
        ["External-File Protection", "外部文件保护"],
        ["Prevent Agent from automatically editing files outside of the workspace", "阻止 Agent 自动编辑工作区外的文件"],
        ["File-Deletion Protection", "文件删除保护"],
        ["Prevent Agent from automatically deleting files", "阻止 Agent 自动删除文件"],
        ["Prevent Agent from deleting files automatically", "阻止 Agent 自动删除文件"],
        ["External-File Protection", "外部文件保护"],
        ["Prevent Agent from automatically editing files outside of the workspace", "阻止 Agent 自动编辑工作区外的文件"],
        ["Prevent Agent from creating or modifying files outside of the workspace automatically", "阻止 Agent 自动在工作区外创建或修改文件"],
        ["Default Location", "默认位置"],
        ["Where to open new agents", "新建智能体的打开位置"],
        ["Pane", "面板"],
        ["Window", "窗口"],
        ["Text Size", "文字大小"],
        ["Adjust the conversation text size", "调整对话文字大小"],
        ["Small", "小"],
        ["Large", "大"],
        ["Extra Large", "超大"],
        ["Auto-Clear Chat", "自动清除对话"],
        ["After periods of inactivity, open the Agent Pane to a new conversation", "闲置一段时间后，打开 Agent 面板时开始新对话"],
        ["Submit with Ctrl + Enter", "使用 Ctrl + Enter 提交"],
        ["When enabled, Ctrl + Enter submits chat and Enter inserts a newline", "启用后，Ctrl + Enter 提交对话，Enter 插入换行"],
        ["Max Tab Count", "最大标签页数"],
        ["Limit how many chat tabs can be open at once", "限制同时打开的对话标签页数量"],
        ["Queue Messages", "消息队列"],
        ["Send after current message", "在当前消息之后发送"],
        ["Stop & send right away", "停止并立即发送"],
        ["Adjust the default behavior of sending a message while Agent is running", "调整 Agent 运行时发送消息的默认行为"],
        ["Usage Summary", "用量摘要"],
        ["When to show the usage summary at the bottom of the chat pane", "何时在聊天面板底部显示用量摘要"],
        ["Always", "始终"],
        ["Never", "从不"],
        ["Auto", "自动"],
        ["Suggest Next Prompt", "建议下一个提示"],
        ["Suggest the next prompt for Agent", "为 Agent 建议下一个提示"],
        ["Contextual suggestions while prompting Agent", "在提示 Agent 时提供上下文建议"],
        ["Agent Autocomplete", "Agent 自动补全"],

        // -- 自动运行网络/沙盒 --
        ["Auto-Run Network Access", "自动运行网络访问"],
        ["Control which network requests are allowed when commands run in the sandbox.", "控制在沙盒中运行命令时允许哪些网络请求。"],
        ["Allow All", "全部允许"],
        ["sandbox.json + Defaults", "sandbox.json + 默认"],
        ["sandbox.json Only", "仅 sandbox.json"],
        ["Command Allowlist", "命令白名单"],
        ["Commands that can run automatically", "可以自动运行的命令"],
        ["Command Denylist", "命令黑名单"],
        ["Commands that should always require user approval, even if they match allowlist patterns", "即使匹配白名单模式，也应始终需要用户批准的命令"],
        ["Smart Allowlist", "智能白名单"],
        ["Use AI-powered command classification to intelligently match commands against allowlist patterns and suggest sandbox modes", "使用 AI 驱动的命令分类来智能匹配白名单模式并建议沙盒模式"],
        ["Choose how Agent runs tools like command execution, MCP, and file writes. Tools will auto-run in a sandbox if possible. If not, they will respect the allowlist or ask for approval.", "选择 Agent 如何运行工具（如命令执行、MCP 和文件写入）。如果可能，工具将在沙盒中自动运行。否则，它们将遵循白名单或请求批准。"],
        ["MCP Allowlist", "MCP 白名单"],
        ["MCP tools that can run automatically. Format: 'server:tool', 'server:*' for all tools from a server, '*:tool' for a tool from any server, or '*:*' for all tools from all servers", "可以自动运行的 MCP 工具。格式：'server:tool'、'server:*' 表示某服务器的所有工具、'*:tool' 表示任意服务器的某工具、'*:*' 表示所有服务器的所有工具"],

        // -- Agent 审查 --
        ["Agent Review", "Agent 审查"],
        ["Auto-Run On Agent Finish", "Agent 完成时自动运行"],
        ["Automatically review your changes for issues after each commit", "每次提交后自动审查更改中的问题"],
        ["Start Agent Review on Commit", "提交时启动 Agent 审查"],
        ["Include Submodules in Agent Review", "在 Agent 审查中包含子模块"],
        ["Include changes from Git submodules in the review", "在审查中包含 Git 子模块的更改"],
        ["Include Untracked Files in Agent Review", "在 Agent 审查中包含未跟踪文件"],
        ["Include untracked files (new files not yet added to Git) in the review", "在审查中包含未跟踪的文件（尚未添加到 Git 的新文件）"],
        ["Default Approach", "默认方式"],
        ["Choose between quick or more thorough, higher-cost analysis", "选择快速或更彻底、更高成本的分析"],
        ["Quick", "快速"],
        ["Deep", "深度"],
        ["Automatically run Review when Agent finishes and has made file changes", "当 Agent 完成并修改了文件时自动运行审查"],

        // -- 提交署名 --
        ["Attribution", "署名"],
        ["Commit Attribution", "提交署名"],
        ["Mark Agent commits as 'Made with Cursor'", "将 Agent 提交标记为'使用 Cursor 制作'"],
        ["PR Attribution", "PR 署名"],
        ["Mark pull requests as made with Cursor", "将拉取请求标记为使用 Cursor 制作"],
        ["Git", "Git"],
        ["Branch Prefix", "分支前缀"],
        ["Prefix for new branches created by Agent (e.g., cursor/, username/)", "Agent 创建新分支的前缀（例如：cursor/、username/）"],

        // -- 格式化 --
        ["Auto Format on Agent Finish", "Agent 完成时自动格式化"],
        ["Automatically format files when the agent finishes", "当智能体完成时自动格式化文件"],

        // -- 浏览器/声音 --
        ["Browser", "浏览器"],
        ["Browser Tab", "浏览器标签"],
        ["Show Localhost Links in Browser", "在浏览器中显示 Localhost 链接"],
        ["Automatically open localhost links in the Browser Tab", "自动在浏览器标签页中打开 localhost 链接"],
        ["Browser automation disabled", "浏览器自动化已禁用"],

        // -- 语音模式 --
        ["Voice Mode", "语音模式"],
        ["Submit Keywords", "提交关键词"],
        ["Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.", "在语音模式下触发自动提交的自定义关键词。仅允许单个词语（无空格）。忽略标点和大小写。"],

        // ==================== 代码补全 (Tab) 页面 ====================
        ["Cursor Tab", "Cursor Tab"],
        ["Enable Cursor Tab", "启用 Cursor Tab"],
        ["Context-aware, multi-line suggestions around your cursor based on recent edits", "基于最近编辑，围绕光标提供上下文感知的多行建议"],
        ["Cursor Prediction", "Cursor 预测"],
        ["Enable Cursor Prediction", "启用 Cursor 预测"],
        ["Partial Accepts", "部分接受"],
        ["Accept the next word of a suggestion via Ctrl+RightArrow", "通过 Ctrl+右箭头 接受建议的下一个词"],
        ["Suggestions While Commenting", "注释时的建议"],
        ["Allow Tab to trigger while in a comment region", "允许在注释区域中触发 Tab"],
        ["Whitespace-Only Suggestions", "仅空白建议"],
        ["Suggest edits like new lines and indentation that modify whitespace only", "建议仅修改空白的编辑，如新行和缩进"],
        ["Cpp Control Token", "Cpp 控制令牌"],
        ["Control tokens control how likely the model is to produce no-ops. Will be replaced with auto-selection", "控制令牌控制模型产生空操作的可能性。将被自动选择替代"],
        ["Auto-Import", "自动导入"],
        ["Imports", "导入"],
        ["Automatically import necessary modules for TypeScript", "自动为 TypeScript 导入必要的模块"],
        ["Enable auto import for Python. This is a beta feature.", "启用 Python 的自动导入。这是一个测试版功能。"],
        ["Auto Import for Python BETA", "Python 自动导入 测试版"],
        ["Auto-imports are temporarily disabled", "自动导入暂时已禁用"],
        ["CPP is temporarily disabled", "CPP 暂时已禁用"],
        ["CPP and auto-imports are temporarily disabled", "CPP 和自动导入暂时已禁用"],
        ["Ignored Files", "忽略的文件"],
        ["Glob patterns for files where Cursor Tab will not suggest", "Cursor Tab 不提供建议的文件 Glob 模式"],

        // ==================== 云端智能体 (Cloud Agents) 页面 ====================
        ["Cloud Agents Unavailable", "云端智能体不可用"],
        ["Cloud Agents require a Git repository in an open folder.", "云端智能体需要在打开的文件夹中有 Git 仓库。"],
        ["Open a Git repository", "打开 Git 仓库"],
        ["Loading Cloud Agents settings...", "正在加载云端智能体设置..."],
        ["GitHub Pull Requests", "GitHub Pull 请求"],
        ["Review PRs, fix CI, address comments, and more directly from Cursor", "直接在 Cursor 中审查 PR、修复 CI、回复评论等"],
        ["Connect Slack", "连接 Slack"],
        ["Accelerate development, shared knowledge, and context across your team", "加速开发，在团队中共享知识和上下文"],
        ["Work with Cloud Agents from Slack", "通过 Slack 使用云端智能体"],
        ["Connect GitHub/GitLab, manage team and user settings, and configure environments", "连接 GitHub/GitLab，管理团队和用户设置，配置环境"],
        ["Manage Settings", "管理设置"],
        ["Configured in the dashboard", "在控制面板中配置"],
        ["Team-Level Repository Control", "团队级别仓库控制"],
        ["Disable AI features in specific repositories based on file pattern", "基于文件模式在特定仓库中禁用 AI 功能"],

        // -- 本地自动化 --
        ["Local Automations", "本地自动化"],
        ["Run recurring agent tasks locally on this machine. Each automation can target a specific model.", "在本机上运行重复的智能体任务。每个自动化可以指定特定模型。"],
        ["New Automation", "新建自动化"],
        ["Automation name", "自动化名称"],
        ["Schedule", "调度"],
        ["Add Time", "添加时间"],
        ["Every day", "每天"],
        ["Weekdays", "工作日"],
        ["Mo", "一"],
        ["Tu", "二"],
        ["We", "三"],
        ["Th", "四"],
        ["Fr", "五"],
        ["Sa", "六"],
        ["Su", "日"],
        ["Create a Cloud Automation pre-filled with this local automation's settings", "使用此本地自动化的设置创建云端自动化"],
        ["No local automations yet. Create one to get started.", "暂无本地自动化。创建一个以开始使用。"],
        ["Loading local automations...", "正在加载本地自动化..."],
        ["Send to Cloud", "发送到云端"],
        ["Name is required.", "名称为必填项。"],
        ["Prompt is required.", "提示为必填项。"],
        ["Cron expression is required.", "Cron 表达式为必填项。"],
        ["Model: Auto", "模型：自动"],

        // ==================== 插件 (Plugins) 页面 ====================
        ["From plugins installed in Cursor", "来自 Cursor 中已安装的插件"],
        ["Include third-party Plugins, Skills, and other configs", "包含第三方插件、技能和其他配置"],
        ["Automatically import agent configs from other tools", "自动从其他工具导入智能体配置"],
        ["Browse Marketplace", "浏览市场"],
        ["Plugin MCP Servers", "插件 MCP 服务器"],
        ["Installed MCP Servers", "已安装的 MCP 服务器"],
        ["Remove local plugin", "移除本地插件"],

        // ==================== 规则、技能、子智能体页面 ====================
        ["User Rules", "用户规则"],
        ["Project Rules", "项目规则"],
        ["User Rule", "用户规则"],
        ["Project Rule", "项目规则"],
        ["User Command", "用户命令"],
        ["Project Command", "项目命令"],
        ["Add Rule", "添加规则"],
        ["Add rule", "添加规则"],
        ["Add new rule", "添加新规则"],
        ["Rules for AI", "AI 规则"],
        ["Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.", "使用规则来指导智能体行为，如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。"],
        ["Create rules to guide Agent behavior", "创建规则来指导 Agent 行为"],
        ["Always applied", "始终应用"],
        ["Apply to Specific Files & Folders", "应用于特定文件和文件夹"],
        ["Agent decides when to apply", "Agent 决定何时应用"],
        ["No Rules Yet", "暂无规则"],
        ["Delete Rule", "删除规则"],
        ["Skills", "技能"],
        ["Provide domain-specific knowledge and workflows for the agent", "为智能体提供领域特定的知识和工作流"],
        ["Skills help the agent accomplish specific tasks", "技能帮助智能体完成特定任务"],
        ["Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.", "技能是帮助智能体完成特定任务的专门能力。智能体会在相关时调用技能，也可以在聊天中使用 / 手动触发。"],
        ["No Skills Yet", "暂无技能"],
        ["Delete Skill", "删除技能"],
        ["Subagents", "子智能体"],
        ["Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.", "为复杂任务创建专门的智能体。子智能体可以被智能体调用，以并行处理专注的工作。"],
        ["Create specialized agents to handle focused tasks", "创建专门的智能体来处理专注的任务"],
        ["No Subagents Yet", "暂无子智能体"],
        ["Delete Subagent", "删除子智能体"],
        ["Commands", "命令"],
        ["Create commands to build reusable workflows", "创建命令以构建可复用的工作流"],
        ["Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.", "创建在聊天中使用 / 前缀触发的可复用工作流。使用命令来标准化流程，使常见任务更高效。"],
        ["No Commands Yet", "暂无命令"],
        ["Delete Command", "删除命令"],
        ["Learn about Rules", "了解规则"],
        ["Learn about Skills", "了解技能"],
        ["Learn about Subagents", "了解子智能体"],
        ["Learn about Commands", "了解命令"],
        ["Learn about Hooks", "了解钩子"],
        ["Open JSON", "打开 JSON"],
        ["Open enterprise config", "打开企业版配置"],
        ["Open project config", "打开项目配置"],
        ["Open user config", "打开用户配置"],

        // ==================== 工具与 MCP 页面 ====================
        ["MCP Servers", "MCP 服务器"],
        ["MCP servers", "MCP 服务器"],
        ["Configure MCP servers in the dashboard to make them available in Cursor on desktop and in the cloud.", "在控制面板中配置 MCP 服务器，使其在桌面和云端的 Cursor 中可用。"],
        ["Team MCP Servers", "团队 MCP 服务器"],
        ["No Team MCP Servers", "暂无团队 MCP 服务器"],
        ["No MCP Tools", "暂无 MCP 工具"],
        ["Add MCP Server", "添加 MCP 服务器"],
        ["Delete MCP Server", "删除 MCP 服务器"],
        ["Tools", "工具"],
        ["Resources", "资源"],
        ["Prompts", "提示词"],
        ["Browser", "浏览器"],
        ["Browser Automation", "浏览器自动化"],
        ["Browser automation disabled", "浏览器自动化已禁用"],
        ["Home MCP Servers", "主页 MCP 服务器"],
        ["Servers available in this workspace.", "此工作区中可用的服务器。"],
        ["User MCP Servers", "用户 MCP 服务器"],
        ["No User MCP Tools", "暂无用户 MCP 工具"],
        ["Add a custom MCP tool in your user MCP config.", "在用户 MCP 配置中添加自定义 MCP 工具。"],
        ["Add Custom MCP", "添加自定义 MCP"],
        ["Configure Team MCP Servers", "配置团队 MCP 服务器"],

        // ==================== 钩子 (Hooks) 页面 ====================
        ["Hooks let you run custom scripts at specific points during the agent's execution to modify behavior, enforce policies, or add custom logging.", "钩子允许您在智能体执行的特定时间点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。"],
        ["Note that paths are relative to the hooks.json file", "注意路径相对于 hooks.json 文件"],
        ["Note that plugin hooks paths are relative to the plugin install path.", "注意插件钩子路径相对于插件安装路径。"],
        ["Configured Hooks", "已配置的钩子"],
        ["No hooks configured", "暂无已配置的钩子"],
        ["No hook executions yet", "暂无钩子执行记录"],
        ["Invalid hooks.json found", "发现无效的 hooks.json"],
        ["Error Output:", "错误输出："],
        ["Input:", "输入："],
        ["Output:", "输出："],
        ["Execution Log", "执行日志"],
        ["Clear log", "清除日志"],

        // ==================== 索引与文档 (Indexing & Docs) 页面 ====================
        ["Codebase", "代码库"],
        ["Codebase Indexing", "代码库索引"],
        ["Codebase indexing", "代码库索引"],
        ["Learn about codebase indexing", "了解代码库索引"],
        ["Codebase Index deleted", "代码库索引已删除"],
        ["Delete Codebase Index?", "删除代码库索引？"],
        ["Delete Index", "删除索引"],
        ["Index New Folders", "索引新文件夹"],
        ["Index Repositories for Instant Grep", "索引仓库以实现即时搜索"],
        ["Automatically index repositories to speed up Grep searches. All data is stored locally.", "自动索引仓库以加速 Grep 搜索。所有数据都存储在本地。"],
        ["Embed codebase for improved contextual understanding and knowledge.", "嵌入代码库以提高上下文理解和知识。"],
        ["but all code is stored locally.", "但所有代码都存储在本地。"],
        ["Files to exclude from indexing in addition to .gitignore.", "除 .gitignore 外要从索引中排除的文件。"],
        ["View included files.", "查看包含的文件。"],
        ["Compute index", "计算索引"],
        ["Pause Indexing", "暂停索引"],
        ["Paused", "已暂停"],
        ["Embedding Model", "嵌入模型"],
        ["Select your preferred embedding model. Delete your index and reload to use it.", "选择您首选的嵌入模型。删除索引并重新加载以使用它。"],
        ["Context", "上下文"],
        ["Hierarchical Cursor Ignore", "分层 Cursor 忽略"],
        ["Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.", "将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。"],
        ["Ignore Files in .cursorignore", "忽略 .cursorignore 中的文件"],
        ["Ignore Symlinks in Cursor Ignore Search", "在 Cursor 忽略搜索中忽略符号链接"],
        ["Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.", "谨慎使用。在 .cursorignore 文件发现期间跳过符号链接。仅在您的仓库有很多符号链接且所有 .cursorignore 文件无需它们即可访问时启用。更改此设置需要重启 Cursor。"],
        ["Configure Ignored Files", "配置忽略的文件"],
        ["Auto-Accept Web Search", "自动接受网络搜索"],
        ["Allow Agent to search the web for relevant information", "允许 Agent 搜索网络以获取相关信息"],
        ["Auto-Parse Links", "自动解析链接"],
        ["Automatically parse links when pasted into Quick Edit (Ctrl+K) input", "粘贴到快速编辑（Ctrl+K）输入时自动解析链接"],
        ["Allow Agent to fetch content from URLs", "允许 Agent 从 URL 获取内容"],
        ["Crawl and index custom resources and developer docs", "爬取和索引自定义资源和开发者文档"],
        ["Add Doc", "添加文档"],
        ["Add documentation to use as context. You can also use @Add in Chat or while editing to add a doc.", "添加文档用作上下文。您还可以在聊天中或编辑时使用 @Add 来添加文档。"],
        ["No Docs Added", "暂无已添加的文档"],
        ["Indexing", "索引"],
        ["Automatically index any new folders with fewer than 50,000 files", "自动索引文件数少于 50,000 的新文件夹"],

        // ==================== 网络 (Network) 页面 ====================
        ["HTTP Compatibility Mode", "HTTP 兼容模式"],
        ["HTTP/2", "HTTP/2"],
        ["HTTP/1.1", "HTTP/1.1"],
        ["HTTP/1.0", "HTTP/1.0"],
        ["HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.", "建议使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。"],
        ["Network Diagnostics", "网络诊断"],
        ["Check network connectivity to all Cursor services", "检查与所有 Cursor 服务的网络连接"],
        ["Required Domains", "必需域名"],
        ["These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.", "这些域名必须可访问才能让 Cursor 正常工作。请将它们添加到防火墙或代理白名单中。"],
        ["Fetch Domain Allowlist", "域名获取白名单"],
        ["Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.", "Agent 可以自动获取的域名。使用 '*' 表示所有域名，'*.example.com' 表示通配子域名。"],
        ["Copy results", "复制结果"],
        ["Copied", "已复制"],
        ["Show Logs", "显示日志"],
        ["Hide Logs", "隐藏日志"],

        // ==================== 测试版 (Beta) 页面 ====================
        ["Background Agents", "后台 Agent"],
        ["Bug Finder", "Bug 查找器"],
        ["Bug finder", "Bug 查找器"],
        ["Invite Team Members", "邀请团队成员"],
        ["Invite teammates", "邀请队友"],
        ["Invite", "邀请"],

        // ==================== 模型 (Models) 页面 ====================
        ["API Key", "API 密钥"],
        ["API Keys", "API 密钥"],
        ["Base URL", "基础 URL"],
        ["Override OpenAI Base URL", "覆盖 OpenAI 基础 URL"],
        ["Change the base URL for OpenAI API requests.", "更改 OpenAI API 请求的基础 URL。"],
        ["OpenAI API Key", "OpenAI API 密钥"],
        ["Anthropic API Key", "Anthropic API 密钥"],
        ["Google API Key", "Google API 密钥"],
        ["Azure OpenAI", "Azure OpenAI"],
        ["AWS Bedrock", "AWS Bedrock"],
        ["Deployment Name", "部署名称"],
        ["Region", "区域"],
        ["Access Key ID", "访问密钥 ID"],
        ["Secret Access Key", "秘密访问密钥"],
        ["Add Model", "添加模型"],
        ["Add model", "添加模型"],
        ["Remove Model", "移除模型"],
        ["Remove model", "移除模型"],
        ["Test Model", "测试模型"],
        ["Add or search model", "添加或搜索模型"],
        ["Enter model name", "输入模型名称"],
        ["Enter your OpenAI API Key", "输入您的 OpenAI API 密钥"],
        ["Enter your Anthropic API Key", "输入您的 Anthropic API 密钥"],
        ["Enter your Google AI Studio API Key", "输入您的 Google AI Studio API 密钥"],
        ["Enter your Azure OpenAI API Key", "输入您的 Azure OpenAI API 密钥"],
        ["Turn Off Anthropic Key", "关闭 Anthropic 密钥"],
        ["Turn Off Google Key", "关闭 Google 密钥"],
        ["Select Custom Chime Sound", "选择自定义提示音"],
        ["Legacy Terminal Tool", "旧版终端工具"],
        ["Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations", "在智能体模式下使用旧版终端工具，适用于不支持的 Shell 配置系统"],
        ["Use a preview box instead of streaming responses directly into the shell", "使用预览框而不是将响应直接流式传输到 Shell 中"],
        ["Collapse Auto-Run Commands", "折叠自动运行命令"],
        ["Collapse auto-run command output by default in Terminal command previews", "在终端命令预览中默认折叠自动运行命令输出"],

        // ==================== 通用 UI 元素 ====================
        ["Save", "保存"],
        ["Cancel", "取消"],
        ["Delete", "删除"],
        ["Edit", "编辑"],
        ["Add", "添加"],
        ["Remove", "移除"],
        ["Create", "创建"],
        ["Reset", "重置"],
        ["Reset All", "全部重置"],
        ["Apply", "应用"],
        ["Close", "关闭"],
        ["Search", "搜索"],
        ["Settings", "设置"],
        ["Preferences", "首选项"],
        ["Configuration", "配置"],
        ["Configure", "配置"],
        ["Edit configuration", "编辑配置"],
        ["Configuration Errors", "配置错误"],
        ["Enable", "启用"],
        ["Disable", "禁用"],
        ["On", "开"],
        ["Off", "关"],
        ["OK", "确定"],
        ["Yes", "是"],
        ["No", "否"],
        ["None", "无"],
        ["All", "全部"],
        ["Default", "默认"],
        ["Custom", "自定义"],
        ["More", "更多"],
        ["Less", "更少"],
        ["Show", "显示"],
        ["Hide", "隐藏"],
        ["Copy", "复制"],
        ["Open", "打开"],
        ["New", "新建"],
        ["Preview", "预览"],
        ["Submit", "提交"],
        ["Confirm", "确认"],
        ["Continue", "继续"],
        ["Back", "返回"],
        ["Next", "下一步"],
        ["Previous", "上一步"],
        ["Done", "完成"],
        ["Loading...", "加载中..."],
        ["Loading", "加载中"],
        ["Retry", "重试"],
        ["Learn more", "了解更多"],
        ["Learn More", "了解更多"],
        ["Dismiss", "关闭"],
        ["Install", "安装"],
        ["Installed", "已安装"],
        ["Uninstall", "卸载"],
        ["Update", "更新"],
        ["Explore", "探索"],
        ["Popular", "热门"],
        ["Trending", "趋势"],
        ["Name", "名称"],
        ["Value", "值"],
        ["Key", "键"],
        ["Status", "状态"],
        ["Actions", "操作"],
        ["Warning", "警告"],
        ["Info", "信息"],
        ["Error", "错误"],
        ["Success", "成功"],
        ["Failed", "失败"],
        ["Pending", "等待中"],
        ["Active", "活动"],
        ["Running", "运行中"],
        ["Syncing", "同步中"],
        ["Initializing", "初始化中"],
        ["Sync", "同步"],
        ["Restart", "重启"],
        ["Download", "下载"],
        ["Import", "导入"],
        ["Export", "导出"],
        ["Applying Changes", "正在应用更改"],
        ["No description", "无描述"],
        ["Get Started", "开始使用"],
        ["Create with Agent", "使用 Agent 创建"],
        ["User", "用户"],
        ["Agent", "智能体"],
        ["10", "10"],
        ["All Files", "所有文件"],
        ["Audio Files", "音频文件"],
        ["Breadcrumb", "面包屑"],
        ["Island", "浮动岛"],
        ["Start Free Trial", "开始免费试用"],
        ["Start free trial", "开始免费试用"],

        // ==================== 菜单栏 (Menu Bar) ====================
        ["File", "文件"],
        ["New Agent", "新建智能体"],
        ["Open Folder", "打开文件夹"],
        ["New Terminal", "新建终端"],
        ["New Browser", "新建浏览器"],
        ["Open Editor Window", "打开编辑器窗口"],
        ["Exit", "退出"],
        ["Undo", "撤销"],
        ["Redo", "重做"],
        ["Cut", "剪切"],
        ["Paste", "粘贴"],
        ["Select All", "全选"],
        ["Open Changes", "打开更改"],
        ["Open Browser", "打开浏览器"],
        ["Open File", "打开文件"],
        ["Open Terminal", "打开终端"],
        ["Help", "帮助"],
        ["Command Palette", "命令面板"],
        ["View License", "查看许可证"],

        // ==================== Command Palette ====================
        ["Search files, actions, agents...", "搜索文件、操作、智能体..."],
        ["Use Voice", "使用语音"],
        ["Pin / Unpin Agent", "固定/取消固定智能体"],
        ["Go Back", "返回"],
        ["Go Forward", "前进"],
        ["Plan Mode", "计划模式"],
        ["Ask Mode", "询问模式"],
        ["Debug Mode", "调试模式"],
        ["Open Marketplace", "打开市场"],
        ["Toggle Full Screen", "切换全屏"],
        ["Mode", "模式"],
        ["View", "视图"],

        // ==================== placeholder 翻译 ====================
        ["AWS Access Key ID", "AWS 访问密钥 ID"],
        ["AWS Secret Access Key", "AWS 秘密访问密钥"]
    ]);

    // 正则模式翻译 - 用于包含动态内容的文本
    var MoShi_FanYi = [
        [/^(\d+) requests? remaining$/i, "$1 次请求剩余"],
        [/^(\d+) of (\d+) requests?$/i, "$1 / $2 次请求"],
        [/^(\d+) premium requests?$/i, "$1 次高级请求"],
        [/^(\d+) files? indexed$/i, "$1 个文件已索引"],
        [/^Indexing (\d+) files?$/i, "正在索引 $1 个文件"],
        [/^(\d+) errors?$/i, "$1 个错误"],
        [/^(\d+) warnings?$/i, "$1 个警告"],
        [/^Version (.+)$/i, "版本 $1"],
        [/^(\d+) tools?$/i, "$1 个工具"],
        [/^(\d+) resources?$/i, "$1 个资源"],
        [/^(\d+) prompts?$/i, "$1 个提示词"],
        [/^Updated (.+) ago$/i, "$1前更新"],
        [/^(\d+) seconds? ago$/i, "$1 秒前"],
        [/^(\d+) minutes? ago$/i, "$1 分钟前"],
        [/^(\d+) hours? ago$/i, "$1 小时前"],
        [/^(\d+) days? ago$/i, "$1 天前"],
        [/^Auto-Run Mode Disabled by Team Admin$/i, "自动运行模式已被团队管理员禁用"],
        [/^Auto-Run Mode Controlled by Team Admin$/i, "自动运行模式由团队管理员控制"],
        [/^Auto-Run Mode Controlled by Team Admin \\(Sandbox Enabled\\)$/i, "自动运行模式由团队管理员控制（沙盒已启用）"],
        [/^Custom cron: (.+)$/i, "自定义 Cron：$1"],
        [/^(.+) at (.+)$/i, "$1 于 $2"],
        [/^Automatically index any new folders with fewer than (\d+) files$/i, "自动索引文件数少于 $1 的新文件夹"],
        [/^(\d+) hooks?$/i, "$1 个钩子"],
        [/^(\d+) automations?$/i, "$1 个自动化"],
        [/^(\d+) rules?$/i, "$1 条规则"],
        [/^(\d+) skills?$/i, "$1 个技能"],
        [/^(\d+) commands?$/i, "$1 个命令"],
        [/^(\d+) subagents?$/i, "$1 个子智能体"]
    ];

    // 需要跳过的 CSS 选择器（编辑器/代码区域/输入区域）
    var TiaoGuo_XuanZeQi = '.monaco-editor, .overflow-guard, .view-lines, .editor-scrollable, .inputarea, .rename-input';

    // 需要跳过的标签名
    var TiaoGuo_BiaoQian = new Set(['TEXTAREA', 'INPUT', 'SCRIPT', 'STYLE', 'CODE', 'PRE', 'NOSCRIPT']);

    // 翻译单个文本节点
    function FanYi_WenBen_JieDian(node) {
        var text = node.textContent;
        if (!text) return;

        var trimmed = text.trim();
        if (!trimmed) return;
        if (trimmed.length > 500) return;

        // 跳过纯数字、纯符号
        if (/^[\d\s.,;:!?@#$%^&*()\-+=<>\/\\|~`'"[\]{}]+$/.test(trimmed)) return;

        // 跳过已包含大量中文的文本（已翻译或本身是中文）
        if (/[\u4e00-\u9fff]/.test(trimmed) && (trimmed.match(/[\u4e00-\u9fff]/g) || []).length > trimmed.length * 0.3) return;

        // 精确匹配翻译
        if (FanYi_CiDian.has(trimmed)) {
            var prefix = text.substring(0, text.indexOf(trimmed));
            var suffix = text.substring(text.indexOf(trimmed) + trimmed.length);
            node.textContent = prefix + FanYi_CiDian.get(trimmed) + suffix;
            return;
        }

        // 正则模式翻译
        for (var i = 0; i < MoShi_FanYi.length; i++) {
            var pair = MoShi_FanYi[i];
            if (pair[0].test(trimmed)) {
                var result = trimmed.replace(pair[0], pair[1]);
                node.textContent = text.replace(trimmed, result);
                return;
            }
        }
    }

    // 翻译元素的属性（title, placeholder, aria-label）
    function FanYi_ShuXing(el) {
        var attrs = ['title', 'aria-label', 'placeholder'];
        for (var i = 0; i < attrs.length; i++) {
            var attrName = attrs[i];
            var val = el.getAttribute(attrName);
            if (val) {
                var trimmed = val.trim();
                if (FanYi_CiDian.has(trimmed)) {
                    el.setAttribute(attrName, FanYi_CiDian.get(trimmed));
                }
            }
        }
    }

    // 检查节点是否在编辑器/代码区域内
    function Shi_BianJiQi_QuYu(node) {
        var el = node.nodeType === Node.TEXT_NODE ? node.parentElement : node;
        if (!el) return true;

        // 快速检查标签名
        if (TiaoGuo_BiaoQian.has(el.tagName)) return true;

        // 检查父级链中是否有编辑器
        try {
            if (el.closest(TiaoGuo_XuanZeQi)) return true;
        } catch (e) {}

        return false;
    }

    // 翻译一棵子树（迭代式，避免栈溢出）
    function FanYi_ZiShu(root) {
        var stack = [root];
        while (stack.length > 0) {
            var node = stack.pop();

            if (node.nodeType === Node.ELEMENT_NODE) {
                if (TiaoGuo_BiaoQian.has(node.tagName)) continue;
                if (node.classList &&
                    (node.classList.contains('monaco-editor') ||
                     node.classList.contains('overflow-guard') ||
                     node.classList.contains('view-lines') ||
                     node.classList.contains('editor-scrollable'))) continue;
                if (node.getAttribute('contenteditable') === 'true') continue;

                FanYi_ShuXing(node);

                var children = node.childNodes;
                for (var i = children.length - 1; i >= 0; i--) {
                    stack.push(children[i]);
                }
            } else if (node.nodeType === Node.TEXT_NODE) {
                if (!Shi_BianJiQi_QuYu(node)) {
                    FanYi_WenBen_JieDian(node);
                }
            }
        }
    }

    // 批处理队列和调度
    var DaiChuLi_JieDian = [];
    var YiDiaoDu = false;

    function TianJia_DaiChuLi(node) {
        DaiChuLi_JieDian.push(node);
        if (!YiDiaoDu) {
            YiDiaoDu = true;
            requestAnimationFrame(ZhiXing_PiLiang_FanYi);
        }
    }

    function ZhiXing_PiLiang_FanYi() {
        var nodes = DaiChuLi_JieDian;
        DaiChuLi_JieDian = [];
        YiDiaoDu = false;

        for (var i = 0; i < nodes.length; i++) {
            try {
                FanYi_ZiShu(nodes[i]);
            } catch (e) {}
        }
    }

    // MutationObserver 回调
    function GuanCha_HuiDiao(mutations) {
        for (var i = 0; i < mutations.length; i++) {
            var m = mutations[i];
            if (m.type === 'childList') {
                var added = m.addedNodes;
                for (var j = 0; j < added.length; j++) {
                    var node = added[j];
                    if (node.nodeType === Node.ELEMENT_NODE || node.nodeType === Node.TEXT_NODE) {
                        TianJia_DaiChuLi(node);
                    }
                }
            } else if (m.type === 'characterData') {
                if (m.target.nodeType === Node.TEXT_NODE) {
                    TianJia_DaiChuLi(m.target);
                }
            }
        }
    }

    // 初始化
    function ChuShiHua() {
        var target = document.documentElement || document.body;
        if (!target) {
            setTimeout(ChuShiHua, 50);
            return;
        }

        var GuanChaQi = new MutationObserver(GuanCha_HuiDiao);
        GuanChaQi.observe(target, {
            childList: true,
            subtree: true,
            characterData: true
        });

        // 初始翻译（延迟执行，等待 DOM 加载）
        setTimeout(function() {
            if (document.body) {
                FanYi_ZiShu(document.body);
            }
        }, 500);

        // 定期补翻（处理异步加载的内容，每3秒一次，共30秒）
        var BuFan_CiShu = 0;
        var BuFan_JiShiQi = setInterval(function() {
            BuFan_CiShu++;
            if (document.body) {
                FanYi_ZiShu(document.body);
            }
            if (BuFan_CiShu >= 10) {
                clearInterval(BuFan_JiShiQi);
            }
        }, 3000);
    }

    // 启动
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', ChuShiHua);
    } else {
        ChuShiHua();
    }
})();
'''


def HuoQu_GongZuoTai_LuJing():
    """获取 workbench 目录完整路径"""
    return os.path.join(CURSOR_AN_ZHUANG_LU_JING, GONG_ZUO_TAI_HTML_XIANG_DUI)  # 拼接完整路径


def HuoQu_HTML_LuJing():
    """获取 workbench.html 完整路径"""
    return os.path.join(HuoQu_GongZuoTai_LuJing(), GONG_ZUO_TAI_HTML_MING)  # HTML 文件路径


def HuoQu_JS_LuJing():
    """获取翻译 JS 文件完整路径"""
    return os.path.join(HuoQu_GongZuoTai_LuJing(), HAN_HUA_JS_MING)  # JS 文件路径


def HuoQu_BeiFen_LuJing():
    """获取备份文件路径"""
    return HuoQu_HTML_LuJing() + BEI_FEN_HOU_ZHUI  # 备份文件路径


def JianCha_YiZhuRu():
    """检查是否已经注入过翻译脚本"""
    LuJing_Html = HuoQu_HTML_LuJing()  # HTML 文件路径
    if not os.path.exists(LuJing_Html):  # 检查文件是否存在
        return False
    with open(LuJing_Html, 'r', encoding='utf-8') as WenJian:  # 以 UTF-8 读取
        NeiRong = WenJian.read()  # 读取全部内容
    return ZHU_RU_BIAO_JI in NeiRong  # 检查注入标记


def ChuangJian_BeiFen():
    """创建 workbench.html 的备份"""
    LuJing_Html = HuoQu_HTML_LuJing()  # 原始文件路径
    LuJing_BeiFen = HuoQu_BeiFen_LuJing()  # 备份文件路径

    if not os.path.exists(LuJing_BeiFen):  # 仅在没有备份时才创建
        shutil.copy2(LuJing_Html, LuJing_BeiFen)  # 复制文件（保留元数据）
        print(f"[备份] 已创建备份: {LuJing_BeiFen}")
    else:
        print(f"[备份] 备份已存在: {LuJing_BeiFen}")


def XieRu_FanYi_JS():
    """将翻译 JavaScript 文件写入 Cursor 目录"""
    LuJing_Js = HuoQu_JS_LuJing()  # JS 文件路径
    with open(LuJing_Js, 'w', encoding='utf-8') as WenJian:  # 以 UTF-8 写入
        WenJian.write(HAN_HUA_JS_NEI_RONG)  # 写入翻译脚本内容
    print(f"[写入] 翻译脚本已写入: {LuJing_Js}")


def ZhuRu_HTML():
    """在 workbench.html 中注入翻译脚本引用"""
    LuJing_Html = HuoQu_HTML_LuJing()  # HTML 文件路径

    with open(LuJing_Html, 'r', encoding='utf-8') as WenJian:  # 读取 HTML
        NeiRong = WenJian.read()  # 读取全部内容

    # 构造注入代码片段
    ZhuRu_DaiMa = f'\n\t{ZHU_RU_BIAO_JI}\n\t<script src="./{HAN_HUA_JS_MING}"></script>\n'

    # 在 </body> 后、workbench.js 之前注入
    if '</body>' in NeiRong:
        NeiRong = NeiRong.replace(
            '</body>',
            f'</body>\n{ZhuRu_DaiMa}'
        )
    else:
        NeiRong = NeiRong.replace(
            '</html>',
            f'{ZhuRu_DaiMa}\n</html>'
        )

    with open(LuJing_Html, 'w', encoding='utf-8') as WenJian:  # 写入修改后的 HTML
        WenJian.write(NeiRong)  # 写入内容

    print(f"[注入] 已在 workbench.html 中注入翻译脚本引用")

    # 更新 product.json 中的校验值，避免 "installation appears to be corrupt" 提示
    GengXin_JiaoYan_Zhi()


def GengXin_JiaoYan_Zhi():
    """更新 product.json 中 workbench.html 的校验哈希值（使用字符串替换保持原始格式）"""
    LuJing_Product = os.path.join(CURSOR_AN_ZHUANG_LU_JING, "resources", "app", "product.json")  # product.json 路径
    LuJing_Html = HuoQu_HTML_LuJing()  # HTML 文件路径

    if not os.path.exists(LuJing_Product):  # 检查 product.json 是否存在
        print(f"[警告] 未找到 product.json: {LuJing_Product}")
        return

    # 计算修改后的 workbench.html 的 SHA256 哈希值（去掉末尾 = 填充符，与 Cursor 原始格式一致）
    with open(LuJing_Html, 'rb') as WenJian:  # 二进制读取
        ShuJu = WenJian.read()  # 读取全部内容
    HaXi_Zhi = base64.b64encode(hashlib.sha256(ShuJu).digest()).decode('utf-8').rstrip('=')  # 去掉 Base64 填充

    # 备份 product.json（仅首次）
    LuJing_Product_BeiFen = LuJing_Product + BEI_FEN_HOU_ZHUI  # 备份路径
    if not os.path.exists(LuJing_Product_BeiFen):  # 仅在没有备份时才创建
        shutil.copy2(LuJing_Product, LuJing_Product_BeiFen)  # 创建备份

    # 读取 product.json 原始文本（保持格式不变）
    with open(LuJing_Product, 'r', encoding='utf-8') as WenJian:  # 读取原始文本
        YuanShi_WenBen = WenJian.read()  # 保留原始格式

    # 用正则精准替换 workbench.html 对应的校验值，不改变文件其他内容
    import re  # 正则表达式
    JiaoYan_Jian = "vs/code/electron-sandbox/workbench/workbench.html"  # 校验键名
    MoShi = re.compile(
        r'("' + re.escape(JiaoYan_Jian) + r'"\s*:\s*")([^"]*?)(")'  # 匹配键值对
    )
    PiPei = MoShi.search(YuanShi_WenBen)  # 查找匹配
    if PiPei:
        XinWenBen = YuanShi_WenBen[:PiPei.start(2)] + HaXi_Zhi + YuanShi_WenBen[PiPei.end(2):]  # 精准替换哈希值
        with open(LuJing_Product, 'w', encoding='utf-8') as WenJian:  # 写回文件
            WenJian.write(XinWenBen)  # 保持原始格式
        print(f"[校验] 已更新 product.json 中的校验值")
    else:
        print(f"[警告] product.json 中未找到 workbench.html 的校验条目")


def HuiFu_JiaoYan_Zhi():
    """恢复 product.json 的原始校验值"""
    LuJing_Product = os.path.join(CURSOR_AN_ZHUANG_LU_JING, "resources", "app", "product.json")  # product.json 路径
    LuJing_Product_BeiFen = LuJing_Product + BEI_FEN_HOU_ZHUI  # 备份路径

    if os.path.exists(LuJing_Product_BeiFen):  # 如果备份存在
        shutil.copy2(LuJing_Product_BeiFen, LuJing_Product)  # 从备份恢复
        os.remove(LuJing_Product_BeiFen)  # 删除备份
        print(f"[校验] 已恢复 product.json 原始校验值")


def HuiFu_YuanShi():
    """恢复原始的 workbench.html（去除注入）"""
    LuJing_Html = HuoQu_HTML_LuJing()  # HTML 文件路径
    LuJing_BeiFen = HuoQu_BeiFen_LuJing()  # 备份文件路径
    LuJing_Js = HuoQu_JS_LuJing()  # JS 文件路径

    if os.path.exists(LuJing_BeiFen):  # 如果备份存在
        shutil.copy2(LuJing_BeiFen, LuJing_Html)  # 从备份恢复
        os.remove(LuJing_BeiFen)  # 删除备份文件
        print(f"[恢复] 已从备份恢复: {LuJing_Html}")
    else:
        print("[恢复] 未找到备份文件，尝试手动移除注入...")
        with open(LuJing_Html, 'r', encoding='utf-8') as WenJian:
            HangLieBiao = WenJian.readlines()  # 按行读取

        XinHang = []  # 新的行列表
        TiaoGuo = False  # 是否在跳过注入区域
        for Hang in HangLieBiao:  # 遍历每一行
            if ZHU_RU_BIAO_JI in Hang:  # 发现注入标记
                TiaoGuo = True  # 开始跳过
                continue
            if TiaoGuo and '<script src="./' + HAN_HUA_JS_MING + '">' in Hang:
                TiaoGuo = False  # 结束跳过
                continue
            if not TiaoGuo:  # 非跳过区域
                XinHang.append(Hang)  # 保留该行

        with open(LuJing_Html, 'w', encoding='utf-8') as WenJian:
            WenJian.writelines(XinHang)  # 写入清理后的内容
        print(f"[恢复] 已手动移除注入内容")

    # 恢复 product.json 的原始校验值
    HuiFu_JiaoYan_Zhi()

    if os.path.exists(LuJing_Js):  # 如果翻译 JS 存在
        os.remove(LuJing_Js)  # 删除翻译 JS 文件
        print(f"[清理] 已删除翻译脚本: {LuJing_Js}")

    print("[完成] 已恢复原始状态")


def ZhuChengXu():
    """主程序入口"""
    print("=" * 60)
    print("  Cursor Settings 页面汉化工具")
    print(f"  时间: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    # 检查命令行参数
    if len(sys.argv) > 1 and sys.argv[1] == '--huifu':  # 恢复模式
        print("\n[模式] 恢复原始文件...")
        HuiFu_YuanShi()  # 执行恢复
        return

    # 检查 Cursor 安装目录
    LuJing_Html = HuoQu_HTML_LuJing()  # HTML 文件路径
    if not os.path.exists(LuJing_Html):  # 检查文件是否存在
        print(f"\n[错误] 未找到 workbench.html: {LuJing_Html}")
        print(f"[提示] 请检查 Cursor 安装路径是否正确: {CURSOR_AN_ZHUANG_LU_JING}")
        sys.exit(1)

    # 检查是否已注入
    if JianCha_YiZhuRu():  # 已经注入过
        print("\n[检测] 翻译脚本已注入，正在更新...")
        XieRu_FanYi_JS()
        GengXin_JiaoYan_Zhi()  # 确保校验值也是最新的
        print("[完成] 翻译脚本已更新，重启 Cursor 生效")
        return

    # 执行注入
    print(f"\n[目标] {LuJing_Html}")
    print("[步骤 1/3] 创建备份...")
    ChuangJian_BeiFen()  # 创建备份

    print("[步骤 2/3] 写入翻译脚本...")
    XieRu_FanYi_JS()  # 写入 JS 文件

    print("[步骤 3/3] 注入 HTML 引用...")
    ZhuRu_HTML()  # 修改 HTML

    print("\n" + "=" * 60)
    print("  [完成] Cursor Settings 页面汉化成功！")
    print("  请重启 Cursor 以查看效果。")
    print("  如需恢复原始状态，运行: python CursorHanHua_GongJu.py --huifu")
    print("=" * 60)


if __name__ == '__main__':
    ZhuChengXu()  # 运行主程序
